platform :ios, '7.0'
source 'http://git.oschina.net/akuandev/Specs.git'

pod 'AFNetworking'
#pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'ActionSheetPicker-3.0'
pod 'RZTransitions', '~> 1.0'
pod 'AVOSCloud'
pod 'MAThemeKit'
pod 'RNBlurModalView', '~> 0.1.0'