platform :ios, '7.0'

pod 'AFNetworking'
#pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'ActionSheetPicker-3.0'
pod 'RZTransitions'
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'MAThemeKit'
pod 'MagicalRecord'
pod 'LMDropdownView'
pod 'RNBlurModalView'
#pod 'JVFloatLabeledTextField'
