platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5'
#pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'ActionSheetPicker-3.0'
pod 'RZTransitions'
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'LeanCloudFeedback'
pod 'MAThemeKit'
pod 'MagicalRecord'
pod 'LMDropdownView', '1.0.0'
pod 'RNBlurModalView'
pod 'JVFloatLabeledTextField'
